"""ComfyUI custom node: hard-lock a spatial region (typically the background) of an LTXV
LATENT for the entire clip.

Install: copy this file to ``ComfyUI/custom_nodes/ltxv_lock_background_region.py`` and restart
ComfyUI (or use its "reload custom nodes" option). A new node "LTXV Lock Background Region"
appears under category ``conditioning/ltxv``.

Why this exists: ComfyUI's own ``LTXVAddGuide`` node has an ``attention_mask`` input, but per
its own tooltip ("Controls per-region conditioning influence via self-attention, multiplied by
strength") that only *biases* attention -- it does not clamp the region. Every frame outside
LTXVAddGuide's explicit frame-0/last-frame anchors is fully free (``noise_mask=1``) regardless
of that mask, so a background can still visibly drift. This node instead writes directly into
the LATENT's own ``noise_mask`` (the same mechanism ``LTXVAddGuide``'s ``replace_latent_frames``
uses for a single frame, generalized here to a spatial region across every frame at once), so
the locked region cannot be regenerated by the sampler at all, for the whole clip.

Where to put it in your graph: right after your existing conditioning/guide nodes (e.g. after
the "First & Last Frame to Video (LTX-2.5)" subgraph's ``LTXVAddGuide`` chain, before the
sampler/``SamplerCustomAdvanced``). It only edits the LATENT dict (``samples`` + ``noise_mask``)
-- it does not touch positive/negative conditioning, so it can slot into an existing LATENT
wire without rewiring anything else.
"""

import comfy.utils
import torch


class LTXVLockBackgroundRegion:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "latent": ("LATENT",),
                "vae": ("VAE",),
                "image": (
                    "IMAGE",
                    {"tooltip": "The composited scene reference (background + characters), one frame."},
                ),
                "mask": (
                    "MASK",
                    {
                        "tooltip": "White = character region (left free to animate). "
                        "Black = background region (locked to `image` for the whole clip)."
                    },
                ),
                "strength": (
                    "FLOAT",
                    {
                        "default": 1.0,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip": "1.0 = background fully locked. Lower values loosen the "
                        "clamp if you want subtle background motion instead of a static one.",
                    },
                ),
            }
        }

    RETURN_TYPES = ("LATENT",)
    FUNCTION = "execute"
    CATEGORY = "conditioning/ltxv"
    DESCRIPTION = (
        "Hard-locks a spatial region (typically the background) of an LTXV latent for every "
        "frame of the clip, instead of only at anchor frames. See node's Python docstring for why."
    )

    def execute(self, latent, vae, image, mask, strength):
        latent_image = latent["samples"]
        batch, channels, latent_length, latent_height, latent_width = latent_image.shape

        noise_mask = latent.get("noise_mask")
        if noise_mask is None:
            noise_mask = torch.ones((batch, 1, latent_length, 1, 1), dtype=torch.float32, device=latent_image.device)
        else:
            noise_mask = noise_mask.clone()
        if noise_mask.shape[3] == 1 or noise_mask.shape[4] == 1:
            noise_mask = noise_mask.expand(-1, -1, -1, latent_height, latent_width).clone()

        # (time, height, width) downscale factors -- ComfyUI's own LTXVAddGuide unpacks this
        # tuple as (time, width, height), which happens to be harmless for the LTXV VAE since
        # its height/width factors are equal (32, 32); named correctly here regardless.
        time_scale_factor, height_scale_factor, width_scale_factor = vae.downscale_index_formula
        target_width = latent_width * width_scale_factor
        target_height = latent_height * height_scale_factor

        # Static video: the reference image repeated for every pixel frame this latent covers,
        # so the encoded latent has exactly `latent_length` frames, matching `latent_image`.
        num_pixel_frames = (latent_length - 1) * time_scale_factor + 1
        pixels = comfy.utils.common_upscale(
            image.movedim(-1, 1), target_width, target_height, "bilinear", crop="center"
        ).movedim(1, -1)[:1, :, :, :3]
        static_video = pixels.expand(num_pixel_frames, -1, -1, -1)
        ref_latent = vae.encode(static_video).to(device=latent_image.device, dtype=latent_image.dtype)

        # Resize the mask to latent spatial resolution and invert: background = NOT character.
        mask = mask[:1].reshape(1, 1, mask.shape[-2], mask.shape[-1]).to(device=latent_image.device)
        mask_r = comfy.utils.common_upscale(mask, latent_width, latent_height, "bilinear", crop="center")
        locked_spatial = (1.0 - mask_r) > 0.5  # (1, 1, H, W)
        locked = locked_spatial.unsqueeze(2).expand(-1, -1, latent_length, -1, -1)  # (1, 1, F, H, W)
        locked_c = locked.expand(-1, channels, -1, -1, -1)  # matches latent_image's channel count

        lock_value = max(0.0, 1.0 - strength)
        latent_image = torch.where(locked_c, ref_latent, latent_image.clone())
        noise_mask = torch.where(locked, torch.full_like(noise_mask, lock_value), noise_mask)

        return ({"samples": latent_image, "noise_mask": noise_mask},)


NODE_CLASS_MAPPINGS = {
    "LTXVLockBackgroundRegion": LTXVLockBackgroundRegion,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "LTXVLockBackgroundRegion": "LTXV Lock Background Region",
}
